name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python '3.x'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: 5ed4899d325c182c45d7d079dfc12fb50f169c7046c14d85564895e5fe1e67b7
        with:
          coverageCommand: make test-coverage
          debug: true
