name: my_linter
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          python -m pip install --upgrade pip
          poetry install
          pip install flake8 pytest
